import random


class Person:
    names = [
        "Adam",
        "Eve",
        "Noah",
        "Liam",
        "Emma",
        "Olivia",
        "Ava",
        "Sophia",
        "Isabella",
        "Mia",
        "Charlotte",
        "Amelia",
        "Harper",
        "Evelyn",
        "Abigail",
        "Ella",
        "Scarlett",
        "Grace",
        "Chloe",
        "Lily",
        "Emily",
        "Elizabeth",
        "Sofia",
        "Avery",
        "Madison",
        "Layla",
        "Penelope",
        "Aria",
        "Riley",
        "Nora",
        "Hannah",
        "Hazel",
        "Zoe",
        "Stella",
        "Violet",
        "Aurora",
        "Savannah",
        "Audrey",
        "Brooklyn",
        "Bella",
        "Claire",
        "Skylar",
        "Lucy",
        "Paisley",
        "Everly",
        "Anna",
        "Caroline",
        "Nova",
        "Genesis",
        "Emilia",
        "Kennedy",
        "Samantha",
        "Maya",
        "Willow",
        "Kinsley",
        "Naomi",
        "Aaliyah",
        "Elena",
        "Sarah",
        "Ariana",
        "Allison",
        "Gabriella",
        "Alice",
        "Madeline",
        "Cora",
        "Ruby",
        "Eva",
        "Serenity",
        "Autumn",
        "Adeline",
        "Hailey",
        "Gianna",
        "Valentina",
        "Isla",
        "Eliana",
        "Quinn",
        "Nevaeh",
        "Ivy",
        "Sadie",
        "Piper",
        "Lydia",
        "Alexa",
        "Josephine",
        "Emery",
        "Julia",
        "Delilah",
        "Arianna",
        "Vivian",
        "Kaylee",
        "Sophie",
        "Brielle",
        "Madelyn",
        "Peyton",
        "Rylee",
        "Clara",
        "Hadley",
        "Melanie",
        "Mackenzie",
        "Reagan",
        "Adalynn",
        "Liliana",
        "Jade",
        "Katherine",
        "Isabelle",
        "Natalia",
        "Raelynn",
        "Maria",
        "Athena",
        "Ximena",
        "Arya",
        "Leilani",
        "Taylor",
        "Faith",
        "Rose",
        "Kylie",
        "Alexandra",
        "Mary",
        "Margaret",
        "Laila",
        "Ashley",
        "Amaya",
        "Eliza",
        "Brianna",
        "Bailey",
        "Andrea",
        "Khloe",
        "Jasmine",
        "Melody",
        "Iris",
        "Isabel",
        "Norah",
        "Annabelle",
        "Valeria",
        "Emerson",
        "Adalyn",
        "Ryleigh",
    ]

    def __init__(self, name=None, age=None, id=None):
        self.name = name if name else random.choice(Person.names)
        self.age = age if age else random.randint(1, 100)
        self.id = id if id else random.randint(100000000, 999999999)

    def print(self):
        print(f"Name: {self.name}")
        print(f"Age: {self.age}")
        print(f"ID: {self.id}")
